plants/urls.py
from django.urls import path

from . import views

app_name = 'plants'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.PlantDetailView.as_view(), name = 'detail'),
    path('new/', views.PlantCreateView.as_view(), name = "create"),
    path('<int:pk>/update/', views.PlantUpdateView.as_view(), name = "update"),
    path('<int:pk>/delete/', views.PlantDeleteView.as_view(), name = "delete"),
    path('family/', views.familyIndex, name='family-index'),
    path('family/<int:pk>/', views.FamilyDetailView.as_view(), name = 'family-detail'),
    path('family/new/', views.FamilyCreateView.as_view(), name = "family-create"),
    path('family/<int:pk>/update/', views.FamilyUpdateView.as_view(), name = "family-update"),
    path('family/<int:pk>/delete/', views.FamilyDeleteView.as_view(), name = "family-delete"),
    path('family_api/', views.familyJsonIndex, name = "family_api"),
    path('<int:pk>/plant-images/new/', views.PlantImagesCreateView.as_view(), name = "plant-images-create"),
    path('plant-images/<int:pk>/update/', views.PlantImagesUpdateView.as_view(), name = "plant-images-update"),
    path('plant-images/<int:pk>/delete/', views.PlantImagesDeleteView.as_view(), name = "plant-images-delete"),
    path('test-page', views.testView,name="test-view"),
]

trfo_plants/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name = 'index.html'), name = "home"),
    path('plants/', include('plants.urls')),
    path('admin/', admin.site.urls),
    #path('create-new-user/', user_views.register, name="register"),
    path('login/', auth_views.LoginView.as_view(template_name = 'users/login.html'), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name = 'users/logout.html'), name="logout"),
]

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

plants/models.py
from django.db import models
from django.urls import reverse

class Family(models.Model):
    family = models.CharField(max_length = 100)
    family_description = models.TextField(null = True)

    def get_absolute_url(self):
        return reverse('plants:family-detail', kwargs={'pk':self.pk})

    def __str__(self):
        family_name = "%s" %str(self.family)
        return(family_name)

# Create your models here.
class plant_basics(models.Model):
    genus = models.CharField(max_length = 500)
    species = models.CharField(max_length = 500)
    symbol = models.CharField(max_length = 6, null = True)
    common_name = models.CharField(max_length = 100, null = True)
    description = models.TextField(null = True)
    image = models.ImageField(upload_to='images/', blank = True, null = True)
    frequency = models.IntegerField(null=True, blank = True)
    family = models.ForeignKey(Family, on_delete = models.PROTECT, null = True)
    
    def __str__(self):
        sci_name = "%s %s" %(str(self.genus), str(self.species))
        return(sci_name)

    def get_absolute_url(self):
        return reverse('plants:detail', kwargs={'pk':self.pk})

class PlantImages(models.Model):
  additional_image = models.ImageField(upload_to='images/', blank = True, null = True)
  additional_image_description = models.TextField(null=True)
  plant_basics = models.ForeignKey(plant_basics, on_delete = models.PROTECT, blank=True, null=True)

  def get_absolute_url(self):
        return reverse('plants:detail', kwargs={'pk':self.plant_basics_id})

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

plants/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import plant_basics, Family, PlantImages

# Create your views here.

def index(request):
    latest_plants = plant_basics.objects.order_by('genus')
    context = {'latest_plants': latest_plants}
    return render(request, 'plants/index.html', context)

class PlantDetailView(generic.DetailView):
    model = plant_basics
    template_name = 'plants/detail.html'

class PlantCreateView(LoginRequiredMixin, generic.CreateView):
    model = plant_basics
    fields =   ['genus',
                'species',
                'symbol',
                'description',
                'image',
                'family'
                ]
class PlantDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = plant_basics
    success_url = reverse_lazy('plants:index')

class PlantUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = plant_basics
    fields = [  'genus',
                'species',
                'symbol',
                'description',
                'image',
                'family'
    ]


# Family Views
def familyIndex(request):
    all_families = Family.objects.order_by('family')
    context = {'all_families': all_families}
    return render(request, 'plants/family_list.html', context)

class FamilyDetailView(generic.DetailView):
    model = Family
    template_name = 'plants/family-detail.html'

class FamilyCreateView(LoginRequiredMixin, generic.CreateView):
    model = Family
    fields =   ['family',
                'family_description'
                ]
class FamilyDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Family
    success_url = reverse_lazy('plants:family-index')

class FamilyUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Family
    fields = [  'family',
                'family_description'
                ]

def familyJsonIndex(request):
    species = plant_basics.objects.order_by('genus').values('genus', 'species','common_name', 'symbol','image','id', 'family__family')
    return JsonResponse({'species': list(species)})

## Additional Images Views

class PlantImagesCreateView(LoginRequiredMixin, generic.CreateView):
    model = PlantImages
    fields =   [
      'additional_image',
      'additional_image_description'
      ]

    def form_valid(self, form):
        form.instance.plant_basics = plant_basics.objects.get(id=self.kwargs.get('pk'))
        return super().form_valid(form)

class PlantImagesDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = PlantImages
    success_url = reverse_lazy('plants:index')

class PlantImagesUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = PlantImages
    fields =   [
      'additional_image',
      'additional_image_description'
      ]
#Random View for testing
def testView(request):
    return render(request, 'plants/test_page.html')

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import UserRegisterForm

def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Your account ahs been created! You can now login.')
            return redirect('login')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form':form})

plants/templates/plants/detail.html
{% extends 'base.html'%}
{% block content%}
<section class="species_detail_wrapper">
  {% if object.image %}
  <div class="species_detail_text_wrapper">
  {% endif %}
  <div class="species_detail_text">

    <h1>{{ object.genus }} {{object.species}}</h1>
    <ul>
        <li><span class="bold">Family:</span> {{object.family}}</li>
        <li><span class="bold">Common Name:</span> {{object.common_name}}</li>
        <li><span class="bold">Symbol:</span> {{object.symbol}}</li>
        <li><span class="bold">Description:</span> {{object.description}}</li>
    </ul>
    <p>
      {% if user.is_authenticated %}
      <a href="{% url 'plants:delete' object.id %} ">Delete Plant</a> |  <a href=" {% url 'plants:index' %}">All Plants</a> | <a href="{% url 'plants:update' object.id %}">Update</a>
      {% endif %}
    </p>
    <h3>Additional Images</h3>
    {% if user.is_authenticated %}
    <a href="{% url 'plants:plant-images-create' object.id %}">Add Additional Images</a>
    {% endif %}
    <ul>
      {% for plant_images in object.plantimages_set.all %}
      <li>
        <img src="{{plant_images.additional_image.url}}" alt="">
        <p>{{ plant_images.additional_image_description }}</p>
        <span>
          <a href="{% url 'plants:plant-images-delete' plant_images.id %}">Delete</a> |
          <a href="{% url 'plants:plant-images-update' plant_images.id%}">Update</a>
        </span>
      </li>
      {% empty %}
      <li>There are no additional images for this species.</li>
      {% endfor%}
    </ul>

  </div>
  {% if object.image %}
  </div>
  {% endif %}
  {% if object.image %}
  <div class="species_detail_image">
      <img src="{{object.image.url}}" alt="Image of {{object.genus}} {{object.species}}">
  </div>
  {% endif %}



</section>



{% endblock %}

plants/templates/plants/family-detail.html
{% extends 'base.html'%}
{% block content%}

<h1>{{ object.family }}</h1>
<p>{{ object.family_description }}</p>
{% if user.is_authenticated %}
<a href="{% url 'plants:family-delete' object.id %} ">Delete Family</a> |  <a href=" {% url 'plants:family-index' %}">All Families</a>
{% endif %}
<ul>
  {% for species in object.plant_basics_set.all %}
    <li><a href="{% url 'plants:detail' species.id %}">{{ species.genus }} {{species.species}}</a></li>
  {% endfor %}
</ul>
{% endblock %}

plants/templates/plants/family_confirm_delete.html
{% extends 'base.html'%}
{% block content%}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
    <a href="{% url 'plants:family-detail' object.id %}">Don't delete</a>
</form>
{% endblock %}

plants/templates/plants/family_form.html
{% extends 'base.html'%}
{% block content%}
<form method="post" enctype="multipart/form-data">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

{% endblock %}

plants/templates/plants/family_list.html
{% extends 'base.html'%}
{% block content%}
<h1 class="page-title">Family List</h1>
<p class="page-tagline">All plants listed by family.</p>
{% if all_families %}
<div class="flex-grid lrg-2 content-wrapper">
  {% for family in all_families %}
  <div class="family-list flex-grid-item">
      <h2><a href="{% url 'plants:family-detail' family.id %}">{{ family.family }}</a></h2>
      <ul>
        {% for species in family.plant_basics_set.all %}
          <li><a href="{% url 'plants:detail' species.id %}">{{ species.genus }} {{species.species}}</a></li>
        {% endfor %}
      </ul>
  </div>
  {% endfor %}
</div>
{% else %}
    <p>No plants are available.</p>
{% endif %}
{% endblock %}

plants/templates/plants/index.html
{% extends 'base.html'%}
{% block content%}
<div class = "content-wrapper">
  <h1>Welcome to the plants database</h1>
  <p>This is a database that houses the BLM Tres Rios Field Office's plants database. Take a look around all of our plants. Do you want a similar database for your organization.  Contact mike@schmidtyworks.com.</p>
  <!--<p><span class="bold">Sort by:</span> <a href="#" class = "sort-select" value="genus">Genus</a> | <a href="#" class = "sort-select" value = "family">Family</a> | <a href="#" class = "sort-select" value = "commonName">Common Name</a> | <a href="#" class="sort-select" value="symbol">Symbol</a></p>-->
  <input type="search" name="search" class="search" placeholder="Enter A Plant Name">
  <p class="sub-heading">Enter a plant genus, species or family to rilter the list</p>
  <div id="plants-list">

  </div>
</div>
{% endblock %}

plants/templates/plants/plant_basics_confirm_delete.html
{% extends 'base.html'%}
{% block content%}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
    <a href="{% url 'plants:detail' object.id %}">Don't delete</a>
</form>
{% endblock %}

plants/templates/plants/plant_basics_form.html
{% extends 'base.html'%}
{% block content%}
<form method="post" enctype="multipart/form-data">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
{% endblock %}

plants/templates/plants/plantimages_confirm_delete.html
{% extends 'base.html'%}
{% block content%}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
    <a href="{% url 'plants:detail' object.id %}">Don't delete</a>
</form>
{% endblock %}

plants/templates/plants/plantimages_form.html
{% extends 'base.html'%}
{% block content%}
<form method="post" enctype="multipart/form-data">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
{% endblock %}

plants/templates/plants/test_page.html
{% extends 'base.html'%}
{% block content%}

<div class="content-wrapper">
  <h1>Plants Test</h1>
  <p>Enter a plant genus, species or family to rilter the list</p>
  <input type="search" name="search" class="search" placeholder="Enter A Plant Name">
</div>

<div class = "suggestions content-wrapper">
</div>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>

<meta charset="utf-8">
<meta name = "viewport" content = "width=device-width, initial-scale=1">
<title>TRFO Plants Database | A digital herbarium. </title>
<link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css" />

</head>
<body>
<div class="wrapper">
  <header class="site-header">
    <img src="{% static 'svg/TRFO_Plant_Logo.svg'%}" class = "logo" alt="Logo">
    <nav class="header-nav">
      <ul>
        <li><a href="{% url 'home' %}">Home</a></li>
        <li><a href="{% url 'plants:index' %}">Browse Plants</a></li>
        {% if user.is_authenticated %}
          <li><a href="{% url 'plants:create' %}" class="link-highlight">Enter A New Plant</a></li>
        {% endif%}
      </ul>
    </nav>
    <div class="header-user-info">
      {% if user.is_authenticated %}
        <p class="header-username">{{user.username}}</p>
      {% endif%}

      {% if user.is_authenticated %}
        <a href="{% url 'logout' %}" class="button header-login">Log Out</a>
      {% else %}
        <a href="{% url 'login' %}" class="button header-login">Log In</a>
      {% endif %}
    </div>

  </header>
  {% if messages %}
      {% for message in messages %}
          <div class="warning-message">
                  {{ message }}
          </div>

      {% endfor %}
  {% endif %}
  <div>
    {% block content %}
    {% endblock %}
  </div>

</div> <!--.wraper-->
<script type="text/javascript" src="{% static 'js/main.min.js' %}"></script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block content %}
<div class="pattern-background">
  <div class="text-box index-text-box">
    <h1>Tres Rios Field Office Plants Database</h1>
    <p>A database of plants curated by the Tres Rios Field Office Wildlife and Assessment Inventory and Monitoring programs.  Developed <a href="http://schmidtynotes.com">Mike Schmidt</a>.</p>
    <a href="{% url "plants:index" %}" class="link-button">Browse Plants</a>
  </div>
  <svg width="100%" height="100%">
		<defs>
			<pattern id="polka-dots" x="0" y="0" width="15" height="15" patternUnits="userSpaceOnUse">
				<circle fill="#00AA83" cx="2" cy="2" r="1" />
			</pattern>
		</defs>

		<rect x="0" y="0" width="100%" height="100%" fill="url(#polka-dots)" />
	</svg>

  </div>
  <div class = "content-wrapper" id="browse-plants">
    <h1 id="browse-plants">Welcome to the plants database</h1>
    <p>This is a database that houses all of the plant found and identified on the BLM Tres Rios Field Office. Take a look around all of our plants. Do you want a similar database for your organization or have questions?  Contact mike@schmidtyworks.com.</p>
    <!--<p><span class="bold">Sort by:</span> <a href="#" class = "sort-select" value="genus">Genus</a> | <a href="#" class = "sort-select" value = "family">Family</a> | <a href="#" class = "sort-select" value = "commonName">Common Name</a> | <a href="#" class="sort-select" value="symbol">Symbol</a></p>-->
    <input type="search" name="search" class="search" placeholder="Enter A Plant Name">
    <p class="sub-heading">Enter a plant genus, species or family to rilter the list</p>
    <div id="plants-list">

    </div>
  </div>
  <script>
    
  </script>
{% endblock %}

users/templates/users/login.html
{% extends 'base.html'%}
{% block content%}
<div class="flex-parent ">
  <div class="card">
    <h2>Login</h2>
    <form  method="POST" class="form"> {% csrf_token %}
      {{form.as_p}}
      <button type="submit" name="button">Log In</button>
    </form>
  </div>
</div>


{% endblock %}

users/templates/users/logout.html
{% extends 'base.html'%}
{% block content%}

<h2>You are now logged out.</h2>
<p>Back to home: <a href="{% url 'home' %}">Home</a></p>



{% endblock %}

users/templates/users/register.html
{% if messages %}
    {% for message in message %}
        {{ message }}
    {% endfor %}
{% endif %}
<form method="POST">{% csrf_token %}
    {{ form.as_p }}
    <button type = "submit">Sign Up</button> | <a href="{% url 'register' %}">Sign In</a>
</form>